version: '3.5'
services:
  redis:
    container_name: 'container_redis_api_keywords'
    image: redis
    command: redis-server --requirepass ApiKeywords@2020!
    ports:
      - '6379:6379'

  mysql:
    image: mysql
    container_name: 'container_mysql_api_keywords'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    ports:
      - '3307:3307'
